### PR TITLE
Better navigation for authenticated users

### LINKED ISSUE #146: Clean up navigation for authorized users
When authentication is enabled, users must currently use a nested navigation bar placed at the top of the content area to switch between their dashboard and profile:

image

This is ugly and unintuitive. It should be redesigned to a dropdown in the top right where the user's name is shown, similar to GitHub's interface:

image

### PR DESCRIPTION
**Pull request by AndrewEckart**
User-specific routes are moved to a dropdown below their name:

image

Fixes #146.

### CODE REVIEW

**Comment by BenGalewsky** [comment]
I was thinking Dashboard would be a top level item (and maybe even the home page) and just _Profile_ would move to this dropdown?

**Comment by AndrewEckart** [comment]
> I was thinking Dashboard would be a top level item (and maybe even the home page) and just _Profile_ would move to this dropdown?

We could make it so that your name itself is a link (to the dashboard), but then you have to click a relatively small target (the arrow to the right) to toggle the dropdown. See [split button dropdowns](https://getbootstrap.com/docs/4.0/components/dropdowns/#split-button-dropdowns) for an example.

Alternately, we could just have "Dashboard" as its own link on the right side and then a small picture (pulled from OAuth) as the dropdown toggle, like this:
image

Final option would be to promote all of the links to the header:
_Dashboard_  _Profile_  _sign-out-icon_
I think this works well for the number of links we have right now.

**Comment by AndrewEckart** [comment]
Would also like to re-brand _Profile_ to _My Account_ at some point, since it also contains things like API tokens now.

**Comment by BenGalewsky** [comment]
Not sure why the dashboard isn't just the home page. Why do we need a link to it apart from the ServiceX logo

**Comment by AndrewEckart** [comment]
I guess my thought was that the home page would eventually contain more information about the deployment itself, where it's hosted, who to contact with issues, metrics, etc. We also need something to serve as a splash page for unauthenticated users.

But I agree that the dashboard should just be the default route at this point, since it's probably what most users are looking for.

**Comment by sthapa** [comment]
Is this deployed on any of the flux instances?  It might help a little bit to see the changes in action

**Comment by AndrewEckart** [comment]
> Is this deployed on any of the flux instances? It might help a little bit to see the changes in action

Just updated `servicex-testing-1` with the correct image so that should take effect in a few minutes.

**Review by sthapa — APPROVED** [review]
LGTM, tried it on servicex-testing-1 and everything seems to be working as intended

**Pull request merged**
