### PR TITLE
Add endpoint for an admin to delete a single user

### PR DESCRIPTION
**Pull request by AndrewEckart**
Closes ssl-hep/ServiceX#150

### CODE REVIEW

**Comment by AndrewEckart** [comment]
> This gets it..

Don't merge just yet, I was going to refactor this to be a DELETE request instead of a POST (more RESTful),

**Comment by BenGalewsky** [comment]
I was going to mention that, but decided that the rest of the JWT where less RESTful and so it would just be cruel to point it out.... We could move the approval endpoint to make it RESTful while we are at it :-)

**Comment by BenGalewsky** [comment]
Please fix conflicts

**Comment by AndrewEckart** [comment]
> Please fix conflicts

Rebased with latest changes.

**Pull request merged**
