### PR TITLE
Add pages for transformation requests

### PR DESCRIPTION
**Pull request by AndrewEckart**
This PR aims to expose more information about transformation requests on the web front end.

The scope currently includes adding two new pages:
- `/transformation-request/<id>` displays detailed information about a single transformation request. Note that `id` here is the autoincremented integer used as the primary key in the database, **not** `request_id`, which is the generated UUID used in many other places throughout the back end.
image
I am not sure if DIDs and selections might be considered sensitive. We could show the submitter's email in addition to (or instead of) their name.
- `/active-requests` displays a table with basic information about all transformation requests with a status of Submitted or Running.
image
We can add more information to this table as desired. For example, it might be useful to display the total number of files and number of files remaining here as well. We could also display the number of workers currently running on the cluster for each transformation request by querying for the deployment using the Kubernetes client.

There was also some minor refactoring, including expanding the `AllTransformationRequests` resource at `/servicex/transformation` to support arbitrary query parameters (translated into `WHERE <param>=<value>` SQL conditions). I thought this would be needed, but it's not, so it could be excised.

A new dependency was added: [humanize](https://pypi.org/project/humanize/)

Remaining items:
- [ ] Add unit tests
- [x] Should be able to link to a transformation request by its UUID (we are not indexing on UUIDs - separate issue?)
- [x] Pages should be private
- [x] Authenticated users should be shown a list of their most recent requests
- [x] Table should be paginated 
- [ ] Pages should link to AMI / rucio-ui, if available
- [x] Should show the # of active workers for each request

### CODE REVIEW

**Comment by BenGalewsky** [comment]
Is the use of the db's primary key in the path more RESTful? If we use the uuid then clients could take users directly to their page. 
This is awesome, by the way!

**Comment by AndrewEckart** [comment]
> Is the use of the db's primary key in the path more RESTful? If we use the uuid then clients could take users directly to their page.
> This is awesome, by the way!

I think it's slightly more RESTful, but more importantly, I didn't want to display the full uuid in the table because it's a bit ugly and was wrapping onto multiple lines. We could probably use uuids in the path and IDs in the UI, or add a second route which queries by uuid and then displays the exact same template.

**Comment by AndrewEckart** [comment]
We had a good discussion about this during our most recent meeting. Some ideas:
- Peter suggests that transformation request pages should link to rucio-ui and AMI (ATLAS Metadata Interface), if applicable.
- Andrew and Ben to investigate how to query the K8s API for the number of workers for a given deployment.
- Pages should require authentication (if enabled).
- Gordon suggests that we should show logged-in users their running requests and 20 most recent requests. I think that the latter is probably sufficient (for most users, their 20 most recent requests will include any active requests)
- Expanding on that, I'm now envisioning a dashboard for common functions which is the default route after logging in. For now, it can just let users download/regenerate their API token and view their 20 most recent requests.

**Comment by AndrewEckart** [comment]
@BenGalewsky Added a function for querying the number of active workers for a given transformation request. We can get any of the information listed [here](https://github.com/kubernetes-client/python/blob/6d64cf67d38337a6fdde1908bdadf047b7118731/kubernetes/docs/AppsV1beta1DeploymentStatus.md) - I went with just `ready_replicas` for now.

I'm having some trouble figuring out how to get access to the `TransformerManager` from my routes, though. Passing it around as a class attribute a la `TransformStart.make_api` seems a bit clunky (web routes are currently implemented as just functions, not classes). Is the transformer manager really something that we expect might change over the lifetime of the application? If not, we can probably make it a global somewhere. Same thing goes for the `namespace` argument in all of the `TransformerManager` methods - if this is always just going to be `config['TRANSFORMER_NAMESPACE']`, it could just be a class attribute.

Ideally, there would be a getter on the `TransformResult` model class like:
```
@property
def active_workers() -> int:
    return transformer_manager.get_active_workers(self.request_id)
    ...
```

**Comment by BenGalewsky** [comment]
@AndrewEckart - the transformer manager is already available to the routes (see [transform_start.py](https://github.com/ssl-hep/ServiceX_App/blob/77019de3b7909d3f7c2c6203afa2b5ccfec67995/servicex/resources/transform_start.py#L63) )

I agree this is clunky, but some of this is needed to keep unit testing sane. I came up with it out of frustration trying to get general purpose Dependency Injection working. I tried a couple of solutions but never managed to get them to work (although at the time I was still pretty new to Python and was under time constraints).

**Comment by AndrewEckart** [comment]
> @AndrewEckart - the transformer manager is already available to the routes (see [transform_start.py](https://github.com/ssl-hep/ServiceX_App/blob/77019de3b7909d3f7c2c6203afa2b5ccfec67995/servicex/resources/transform_start.py#L63) )
> 
> I agree this is clunky, but some of this is needed to keep unit testing sane. I came up with it out of frustration trying to get general purpose Dependency Injection working. I tried a couple of solutions but never managed to get them to work (although at the time I was still pretty new to Python and was under time constraints).
> 
> 

Right, this approach doesn't work for web routes because they are not classes like `TransformStart` and other API resources.

I'll try to find another dependency injection strategy.

**Comment by gordonwatts** [comment]
I mean the following to be kept in the backs of our minds, not at the top, and not to affect how we show the information. But it is the case that we sometimes submit the same request against 50 Monte Carlo samples all at once. This will turn into 50 requests. Further, depending on how we tackle systematic errors, you might get a ballooning due to that (another x10 or something?). So it is possible that one will want to look back more than 20 submissions, and the idea of some sort of title is a good one.

**Comment by AndrewEckart** [comment]
> I mean the following to be kept in the backs of our minds, not at the top, and not to affect how we show the information. But it is the case that we sometimes submit the same request against 50 Monte Carlo samples all at once. This will turn into 50 requests. Further, depending on how we tackle systematic errors, you might get a ballooning due to that (another x10 or something?). So it is possible that one will want to look back more than 20 submissions, and the idea of some sort of title is a good one.

I added pagination. If there are more than 20, you can page through to the beginning.

**Comment by AndrewEckart** [comment]
Changed the implementation of the `/servicex/transformation/<id>/deployment-status` endpoint slightly (it now returns all deployment status information, not just the # of ready replicas). Added a column to the requests table which live-updates via AJAX requests to this endpoint on a timer.

[Demo](https://drive.google.com/file/d/1BDmZ5Eu1XQ40q-LLDSjMaUUaMkZHCqDb/view?usp=sharing)

Still some weirdness here - the status column does not live-update, and the `deployment-status` endpoint returns a 404 both before the deployment is created (when a request is Submitted, but not yet Running) and after the request is completed.

**Comment by AndrewEckart** [comment]
Superseded by #90, #101, #102, #105, #108, and #109.

**Pull request closed without merging**
