### PR TITLE
New direct elastic removal

### PR DESCRIPTION
**Pull request by ivukotic**

### CODE REVIEW

**Review by AndrewEckart — CHANGES_REQUESTED** [review]
Please remove any config values related to Elasticsearch from the template configuration file (`app.conf.template` in the project root directory).

Everything else looks good - tests still pass, and there are no other references to Elasticsearch in the codebase.

**Comment by ivukotic** [comment]
> Please remove any config values related to Elasticsearch from the template configuration file (`app.conf.template` in the project root directory).
> 
> Everything else looks good - tests still pass, and there are no other references to Elasticsearch in the codebase.

We will still need these values for the filebeats logging. I can remove them now and add them back in with filebeats, or can leave them in and simply repurpose it. Which one do you prefer?

**Comment by AndrewEckart** [comment]
> > Please remove any config values related to Elasticsearch from the template configuration file (`app.conf.template` in the project root directory).
> > Everything else looks good - tests still pass, and there are no other references to Elasticsearch in the codebase.
> 
> We will still need these values for the filebeats logging. I can remove them now and add them back in with filebeats, or can leave them in and simply repurpose it. Which one do you prefer?

Remove and put them back with filebeats, to keep things internally consistent at any given commit on the main branch.

**Comment by AndrewEckart** [comment]
@ivukotic 

I think we also need an accompanying PR for the [Helm chart repo](https://github.com/ssl-hep/ServiceX) to remove any references / config values for Elasticsearch there as well.

**Comment by ivukotic** [comment]
> > > Please remove any config values related to Elasticsearch from the template configuration file (`app.conf.template` in the project root directory).
> > > Everything else looks good - tests still pass, and there are no other references to Elasticsearch in the codebase.
> > 
> > 
> > We will still need these values for the filebeats logging. I can remove them now and add them back in with filebeats, or can leave them in and simply repurpose it. Which one do you prefer?
> 
> Remove and put them back with filebeats, to keep things internally consistent at any given commit on the main branch.

done

**Comment by ivukotic** [comment]
> @ivukotic
> 
> I think we also need an accompanying PR for the [Helm chart repo](https://github.com/ssl-hep/ServiceX) to remove any references / config values for Elasticsearch there as well.

done

**Review by AndrewEckart — APPROVED** [review]

**Pull request merged**
