### PR TITLE
Replace flask-restful with flask-restx

### LINKED ISSUE #50: Flask-RESTful is unmaintained
Per flask-restful/flask-restful#883, the library is no longer being maintained. Upstream issues affecting us such as vimalloc/flask-jwt-extended#86 (errors are not handled correctly when decoding a JWT) may never be fixed. Proposal is to move to the recommended alternative, [Flask-RESTX](https://github.com/python-restx/flask-restx).

### LINKED ISSUE #51: Distinguish between API resources and web frontend
# Story
_As a ServiceX developer I want to distinguish between frontend routes and API resources_

# Acceptance Criteria
1. API resources are placed in a subdirectory, e.g. `https://<servicex-host>/api/v1/servicex/transformation`
2. User management API endpoints should be organized under `api/v1/user/...`

# Assumptions
1. A subdirectory is preferable to a subdomain (`api.<servicex-host>`) because both are being served by the same Flask app.

### PR DESCRIPTION
**Pull request by AndrewEckart**
[Flask-RESTful](https://github.com/flask-restful/flask-restful) is unmaintained. [Flask-RESTX](https://github.com/python-restx/flask-restx) is a drop-in replacement for Flask-RESTful, as it is a fork of a fork ([Flask-RESTPlus](https://github.com/noirbizarre/flask-restplus) was the intermediate fork).

Regarding version numbers, `flask-restx==0.2.0` would be an acceptable version, but my opinion is that there is no need to freeze versions on the develop branch (except any dependencies we have chosen not to upgrade for some specific reason). During the release process, we can create a release branch (e.g. v1.0.0-RC.2) and then freeze the dependencies there, which guarantees the release will remain stable. If we freeze the develop branch, we do not benefit from improvements made to any of our dependencies.

Closes #50
Closes #51

### CODE REVIEW

**Comment by BenGalewsky** [comment]
Please fix conflicts

**Comment by AndrewEckart** [comment]
Let's hold off on this for now. It seems that Flask-RESTX attempts to automatically document all API endpoints using a tool called [Swagger UI](https://flask-restx.readthedocs.io/en/latest/swagger.html) and serve the docs at `/`. This could actually be a useful feature for us, but right now it's conflicting with our home page, so we need to figure out #51 - how to separate our frontend web routes from our API resources (most likely using Flask's [Blueprint](https://flask.palletsprojects.com/en/1.1.x/blueprints/) concept).

**Comment by AndrewEckart** [comment]
Okay, I went ahead and refactored all of the API resources into a Blueprint (Flask's version of a module), which is then registered with a prefix of `/api/v1` - all API endpoints now begin with this prefix (hardcoded for now, but we can change it if we want). This will require a minor update to the Python client, but improves the organization of the Flask app and even allows us to support multiple versions of our API simultaneously in the future should we make breaking changes. This closes #51.

As mentioned above, Flask-RESTX autogenerates some basic documentation which is displayed via Swagger UI at the base API endpoint (i.e. `/api/v1`). The accuracy of the documentation can be improved using the `@api.doc` decorator. Swagger UI also supports interactively testing endpoints from the docs (like an embedded Postman). This feature doesn't add much value unless endpoints are actually decorated, so I would lean towards disabling it.

**Comment by BenGalewsky** [comment]
We can't move the REST endpoints without considering the Ingress controller in the helm chart. The endpoints have been organized to prevent out-of-cluster access to the internal endpoints that DID Finder, Preflight, and Transformer interact with on an unauthenticated basis

**Comment by BenGalewsky** [comment]
Let's not merge this - we can tackle this when we upgrade to flask2

**Pull request closed without merging**
