### PR TITLE
Query transformation requests by submitting user

### LINKED ISSUE #185: See transformation requests submitted by a user
# Story
_As a ServiceX user I want to easily view my running transformation requests and my request history._

# Assumptions
1. User and TransformRequest models should have a one-to-many relationship

# Acceptance Criteria
1. A bidirectional relationship is established between the UserModel and TransformRequest model. TransformRequest has a foreign key for the submitting user.
2. A db migration script is provided.
3. Users can query for their own TransformRequests. Data is returned as a list in JSON, which can be displayed on web or by Python client.
4. The endpoint to query for all TransformRequests is protected; only admins should be able to make an unfiltered query.

### PR DESCRIPTION
**Pull request by AndrewEckart**
The scope of this PR is as follows:
- Create a one-to-many relationship between the UserModel and TransformRequest model, add a `submitted_by` property to new TransformRequests, and add a db migration script
- Support a `?submitted_by=<user_id>` query parameter at the existing `GET /transformation` endpoint to return all transformation requests submitted by the specified user.
- If auth is enabled, add security to this endpoint. A TransformRequest (or list of TransformRequests) can only be requested by admins or a user who submitted the request(s). In other words, you can only pass your own user ID to `submitted_by` unless you are an admin. Admins can still retrieve the list of all requests in the database via `GET /transformation` with no query parameters.

Open questions:
- ~~RE: the database migration, TransformRequests made on RC2 will not have a `submitted_by` property. If we want to preserve the existing data, we cannot make this column non-nullable. Should we drop the requests table and recreate it instead?~~ - `submitted_by` actually must be nullable for when auth is disabled.
- ~~As written, the `<user_id>` used for these queries is the id column in the users table, which are just sequential integers. Are the frontends even aware of these IDs? On the web, the current user id is available in the session data (once RC3 auth is merged), but we can also store it in the JWTs so that it will be available to the Python client as well.~~ - out of scope, though we can add more info to the JWT in a separate PR

Fixes ssl-hep/ServiceX#185. This is only the backend work. There is still frontend work to be done on the web (and possibly in the Python client as well) to take advantage of the new endpoint, but that can be done in a separate PR.

### CODE REVIEW

**Comment by BenGalewsky** [comment]
Please fix conflicts with develop

**Comment by AndrewEckart** [comment]
Partially rewritten. Scope of the latest changes:
- Move code to find which user submitted a request to a method on `ServiceXResource`
- Split `QueryTransformationRequest` resource into two properly RESTful resources as follows
  - `GET /transformation` or `GET /transformation?submitted_by=<user_id>` to get a list of transformation requests
  - `GET /transformation/<request_id>` to get a single transformation request
- Add tests for both endpoints

I was going to change `/transformation` to `/transformations`, since it looks like it's more common to use the plural, but given that all of the other endpoints use the singular and it would require an update to the frontend I'll leave it for now.

**Comment by BenGalewsky** [comment]
What about the following endpoints? Shouldn't they disallow users seeing other user's requests?
-  `/servicex/transformation/<string:request_id>/status`
- `/servicex/transformation/<string:request_id>/errors`

Shouldn't `/servicex/transformation` just default to transformations that belong to the logged in user? We can either stick the id into the JWT, or query the user like we are doing now.

It's totally fine to truncate the requests table for the upgrade to RC3 - no useful data in there

**Comment by BenGalewsky** [comment]
Add unit test for submitting transform request when auth is deactivated

**Comment by AndrewEckart** [comment]
> Shouldn't `/servicex/transformation` just default to transformations that belong to the logged in user? We can either stick the id into the JWT, or query the user like we are doing now.

How would an admin request all transformations, then? We'd need to create a new endpoint. I think the RESTful thing to do is to use query parameters.

One option is to simply respond to non-admin requests without query params with all of their own transforms rather than a 401, but then we get different behavior for admins and non-admins which could be misleading.

**Comment by AndrewEckart** [comment]
> What about the following endpoints? Shouldn't they disallow users seeing other user's requests?
> 
> * `/servicex/transformation/<string:request_id>/status`
> * `/servicex/transformation/<string:request_id>/errors`

Done, but it required some code/test duplication which is unfortunately unavoidable without creating another authorization decorator such as `@can_access_transform`, which I can do if necessary.

**Comment by AndrewEckart** [comment]
> Add unit test for submitting transform request when auth is deactivated

Every test in `tests/resources/test_submit_transformation_request.py` uses a client with auth deactivated. This is because the resource is decorated with `@auth_required`, which is already tested in `tests/test_decorators.py`.

What's actually untested at the moment are these lines in `SubmitTransformationRequest`, since the if condition is always false when auth is deactivated and always true when it is (unless the user who submitted the request was deleted by an admin):
```
            user = self.get_requesting_user()
            if user:
                request_rec.submitted_by = user.id
```

**Comment by AndrewEckart** [comment]
The `TransformationRequest.submitted_by` column actually has to be nullable in case auth is disabled. This greatly simplifies the database migration - no need to drop/recreate all of the tables.

**Comment by AndrewEckart** [comment]
Removed check to prevent others users from accessing one's transformation requests.

**Review by BenGalewsky — APPROVED** [review]
Thanks - glad we got this in for RC3

**Pull request merged**
